version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    # .env ファイルを読み込んでコンテナ内に環境変数を渡す
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - init_sql:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  init_sql:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/database
  postgres_data:
    driver: local


