import { GoogleLocationFoodMenu } from "@/main/model/LocationModel";

export const testEditedMenus: GoogleLocationFoodMenu[] = [
    {
        labels: [{ displayName: "Menu", description: null, languageCode: null }],
        sourceUrl: null,
        sections: [
            {
                labels: [{ displayName: '編集されたセクション', description: null, languageCode: null }],
                items: [
                    {
                        labels: [{ displayName: '編集された商品1', description: null, languageCode: null }],
                        attributes: {
                            price: { units: '1500', currencyCode: 'JPY', nanos: null },
                            spiciness: null,
                            allergen: null,
                            dietaryRestriction: null,
                            nutritionFacts: null,
                            ingredients: null,
                            servesNumPeople: null,
                            preparationMethods: null,
                            portionSize: null,
                            mediaKeys: null,
                        },
                        options: null,
                    },
                    {
                        labels: [{ displayName: '編集された商品2', description: null, languageCode: null }],
                        attributes: {
                            price: { units: '2500', currencyCode: 'JPY', nanos: null },
                            spiciness: null,
                            allergen: null,
                            dietaryRestriction: null,
                            nutritionFacts: null,
                            ingredients: null,
                            servesNumPeople: null,
                            preparationMethods: null,
                            portionSize: null,
                            mediaKeys: null,
                        },
                        options: null,
                    },
                ],
            },
            {
                labels: [{ displayName: "■…コース…■", description: null, languageCode: null }],
                items: [
                    {
                        labels: [{ displayName: "【ランチＡコース＜11：00-15：00＞】熟成生サムギョプサル食べ放題コース90分1880円！", description: null, languageCode: null }],
                        attributes: {
                            price: { currencyCode: "JPY", units: "2068", nanos: null },
                            spiciness: null,
                            allergen: null,
                            dietaryRestriction: null,
                            nutritionFacts: null,
                            ingredients: null,
                            servesNumPeople: null,
                            preparationMethods: null,
                            portionSize: null,
                            mediaKeys: null,
                        },
                        options: null,
                    },
                    {
                        labels: [{ displayName: "【ランチBコース＜11：00-15：00＞】熟成生肉セット食べ放題コース90分2150円！", description: null, languageCode: null }],
                        attributes: {
                            price: { currencyCode: "JPY", units: "2365", nanos: null },
                            spiciness: null,
                            allergen: null,
                            dietaryRestriction: null,
                            nutritionFacts: null,
                            ingredients: null,
                            servesNumPeople: null,
                            preparationMethods: null,
                            portionSize: null,
                            mediaKeys: null,
                        },
                        options: null,
                    },
                    {
                        labels: [{ displayName: "【ランチCコース＜11：00-15：00＞】プレミアム肉セット食べ放題コース90分2280円！", description: null, languageCode: null }],
                        attributes: {
                            price: { currencyCode: "JPY", units: "2508", nanos: null },
                            spiciness: null,
                            allergen: null,
                            dietaryRestriction: null,
                            nutritionFacts: null,
                            ingredients: null,
                            servesNumPeople: null,
                            preparationMethods: null,
                            portionSize: null,
                            mediaKeys: null,
                        },
                        options: null,
                    },
                    {
                        labels: [{ displayName: "【ランチDコース＜11：00-15：00＞】チーズタッカルビ食べ放題コース90分1580円！", description: null, languageCode: null }],
                        attributes: {
                            price: { currencyCode: "JPY", units: "1738", nanos: null },
                            spiciness: null,
                            allergen: null,
                            dietaryRestriction: null,
                            nutritionFacts: null,
                            ingredients: null,
                            servesNumPeople: null,
                            preparationMethods: null,
                            portionSize: null,
                            mediaKeys: null,
                        },
                        options: null,
                    },
                    {
                        labels: [{ displayName: "【ディナーＡコース＜15：00-23：30＞】熟成生サムギョプサル食べ放題コース90分1980円！", description: null, languageCode: null }],
                        attributes: {
                            price: { currencyCode: "JPY", units: "2178", nanos: null },
                            spiciness: null,
                            allergen: null,
                            dietaryRestriction: null,
                            nutritionFacts: null,
                            ingredients: null,
                            servesNumPeople: null,
                            preparationMethods: null,
                            portionSize: null,
                            mediaKeys: null,
                        },
                        options: null,
                    },
                    {
                        labels: [{ displayName: "【飲み放題付き『ディナーＡコース』】熟成生サムギョプサル食べ放題90分3560円♪", description: null, languageCode: null }],
                        attributes: {
                            price: { currencyCode: "JPY", units: "3916", nanos: null },
                            spiciness: null,
                            allergen: null,
                            dietaryRestriction: null,
                            nutritionFacts: null,
                            ingredients: null,
                            servesNumPeople: null,
                            preparationMethods: null,
                            portionSize: null,
                            mediaKeys: null,
                        },
                        options: null,
                    },
                    {
                        labels: [{ displayName: "【ディナーBコース＜15：00-23：30＞】熟成生肉セット食べ放題コース90分2280円！", description: null, languageCode: null }],
                        attributes: {
                            price: { currencyCode: "JPY", units: "2508", nanos: null },
                            spiciness: null,
                            allergen: null,
                            dietaryRestriction: null,
                            nutritionFacts: null,
                            ingredients: null,
                            servesNumPeople: null,
                            preparationMethods: null,
                            portionSize: null,
                            mediaKeys: null,
                        },
                        options: null,
                    },
                    {
                        labels: [{ displayName: "【飲み放題付き『ディナーBコース』】熟成生肉セット食べ放題コース90分3860円！", description: null, languageCode: null }],
                        attributes: {
                            price: { currencyCode: "JPY", units: "4246", nanos: null },
                            spiciness: null,
                            allergen: null,
                            dietaryRestriction: null,
                            nutritionFacts: null,
                            ingredients: null,
                            servesNumPeople: null,
                            preparationMethods: null,
                            portionSize: null,
                            mediaKeys: null,
                        },
                        options: null,
                    },
                    {
                        labels: [{ displayName: "【ディナーCコース＜15：00-23：30＞】プレミアム肉セット食べ放題コース90分2480円！", description: null, languageCode: null }],
                        attributes: {
                            price: { currencyCode: "JPY", units: "2728", nanos: null },
                            spiciness: null,
                            allergen: null,
                            dietaryRestriction: null,
                            nutritionFacts: null,
                            ingredients: null,
                            servesNumPeople: null,
                            preparationMethods: null,
                            portionSize: null,
                            mediaKeys: null,
                        },
                        options: null,
                    },
                    {
                        labels: [{ displayName: "【飲み放題付き『ディナーCコース』】プレミアム肉セット食べ放題コース90分4060円！", description: null, languageCode: null }],
                        attributes: {
                            price: { currencyCode: "JPY", units: "4466", nanos: null },
                            spiciness: null,
                            allergen: null,
                            dietaryRestriction: null,
                            nutritionFacts: null,
                            ingredients: null,
                            servesNumPeople: null,
                            preparationMethods: null,
                            portionSize: null,
                            mediaKeys: null,
                        },
                        options: null,
                    },
                    {
                        labels: [{ displayName: "【ディナーDコース＜15：00-23：30＞】チーズタッカルビ食べ放題コース90分1680円！", description: null, languageCode: null }],
                        attributes: {
                            price: { currencyCode: "JPY", units: "1848", nanos: null },
                            spiciness: null,
                            allergen: null,
                            dietaryRestriction: null,
                            nutritionFacts: null,
                            ingredients: null,
                            servesNumPeople: null,
                            preparationMethods: null,
                            portionSize: null,
                            mediaKeys: null,
                        },
                        options: null,
                    },
                    {
                        labels: [{ displayName: "【飲み放題付き『ディナーDコース』】チーズタッカルビ食べ放題コース90分3260円！", description: null, languageCode: null }],
                        attributes: {
                            price: { currencyCode: "JPY", units: "3586", nanos: null },
                            spiciness: null,
                            allergen: null,
                            dietaryRestriction: null,
                            nutritionFacts: null,
                            ingredients: null,
                            servesNumPeople: null,
                            preparationMethods: null,
                            portionSize: null,
                            mediaKeys: null,
                        },
                        options: null,
                    },
                    {
                        labels: [{ displayName: "【大人気】コギちゃんUFOチキン『プレーン、ヤンニョム、醤油』1,390円♪", description: null, languageCode: null }],
                        attributes: {
                            price: { currencyCode: "JPY", units: "1529", nanos: null },
                            spiciness: null,
                            allergen: null,
                            dietaryRestriction: null,
                            nutritionFacts: null,
                            ingredients: null,
                            servesNumPeople: null,
                            preparationMethods: null,
                            portionSize: null,
                            mediaKeys: null,
                        },
                        options: null,
                    },
                ],
            },
        ],
        cuisines: null,
    },
];
