/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/store/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 新しい店舗を作成
         * @description
         *                 認証されたユーザーの新しい店舗を作成します。
         *                 Request Bodyには店舗名の文字列を含めます。
         *                 認証されていない場合は、status 401 Unauthorized を返します。(Bodyは StoreErrorResponse)
         *                 店舗の作成に成功した場合は、status 201 Created を返します。(Bodyは StoreResponse)
         *
         */
        post: operations["createStore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/google/places/autocomplete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Google Places API: 場所Idと場所名の候補リストを取得
         * @description Google Places APIを使用して、場所Idと場所名の候補リストを取得します。
         */
        post: operations["postPlacesAutoComplete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/brand/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 新しいブランドを作成
         * @description
         *                 認証されたユーザーの新しいブランドを作成します。
         *                 Request Bodyにはブランド名の文字列を含めます。
         *                 認証されていない場合は、status 401 Unauthorized を返します。(Bodyは BrandErrorResponse)
         *                 ブランドの作成に成功した場合は、status 201 Created を返します。(Bodyは BrandResponse)
         *
         */
        post: operations["createBrand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/store/update/name": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 店舗名を更新
         * @description
         *                 認証されたユーザーの店舗名を更新します。
         *                 Request Bodyには新しい店舗名の文字列を含めます。
         *                 認証されていない場合は、status 401 Unauthorized を返します。(Bodyは StoreErrorResponse)
         *                 店舗名の更新に成功した場合は、status 200 OK を返します。(Bodyは StoreResponse)
         *
         */
        patch: operations["updateStoreName"];
        trace?: never;
    };
    "/api/store/update/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 店舗のGoogleアカウントとロケーションを更新
         * @description
         *                 認証されたユーザーの店舗のGoogleアカウントとロケーションを同時に更新します。
         *                 Request Bodyには新しいGoogleアカウントIDとGoogleロケーションIDの文字列を含めます。
         *                 認証されていない場合は、status 401 Unauthorized を返します。(Bodyは StoreErrorResponse)
         *                 Googleアカウントとロケーションの更新に成功した場合は、status 200 OK を返します。(Bodyは StoreResponse)
         *
         */
        patch: operations["updateStoreGoogle"];
        trace?: never;
    };
    "/api/store/update/google/location": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 店舗のGoogleロケーションを更新
         * @description
         *                 認証されたユーザーの店舗のGoogleロケーションを更新します。
         *                 Request Bodyには新しいGoogleロケーションIDの文字列を含めます。
         *                 認証されていない場合は、status 401 Unauthorized を返します。(Bodyは StoreErrorResponse)
         *                 Googleロケーションの更新に成功した場合は、status 200 OK を返します。(Bodyは StoreResponse)
         *
         */
        patch: operations["updateStoreGoogleLocation"];
        trace?: never;
    };
    "/api/store/update/google/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 店舗のGoogleアカウントを更新
         * @description
         *                 認証されたユーザーの店舗のGoogleアカウントを更新します。
         *                 Request Bodyには新しいGoogleアカウントIDの文字列を含めます。
         *                 認証されていない場合は、status 401 Unauthorized を返します。(Bodyは StoreErrorResponse)
         *                 Googleアカウントの更新に成功した場合は、status 200 OK を返します。(Bodyは StoreResponse)
         *
         */
        patch: operations["updateStoreGoogleAccount"];
        trace?: never;
    };
    "/api/store/update/brand": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 店舗のブランドを更新
         * @description
         *                 認証されたユーザーの店舗のブランドを更新します。
         *                 Request Bodyには新しいブランドIDの文字列を含めます。
         *                 認証されていない場合は、status 401 Unauthorized を返します。(Bodyは StoreErrorResponse)
         *                 ブランドの更新に成功した場合は、status 200 OK を返します。(Bodyは StoreResponse)
         *
         */
        patch: operations["updateStoreBrand"];
        trace?: never;
    };
    "/api/brand/name": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * ブランド名を更新
         * @description
         *                 認証されたユーザーのブランド名を更新します。
         *                 Request Bodyには新しいブランド名の文字列を含めます。
         *                 認証されていない場合は、status 401 Unauthorized を返します。(Bodyは BrandErrorResponse)
         *                 ブランド名の更新に成功した場合は、status 200 OK を返します。(Bodyは BrandListApiResponse)
         *
         */
        patch: operations["updateBrandName"];
        trace?: never;
    };
    "/api/user/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ユーザー情報を取得
         * @description
         *                 ユーザーの情報を取得します。
         *                 認証されていない場合は、status 401 Unauthorized を返します。(Bodyは UserApiResponse)
         *                 既に登録されている場合は、status 200 OK を返します。(Bodyは UserApiResponse)
         *
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 店舗情報を取得
         * @description
         *                 指定された店舗IDの店舗情報を取得します。
         *                 認証されていない場合は、status 401 Unauthorized を返します。(Bodyは StoreErrorResponse)
         *                 店舗が存在しない場合は、status 404 Not Found を返します。(Bodyは StoreErrorResponse)
         *
         */
        get: operations["getStore"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/store/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ユーザーが持つ店舗一覧を取得
         * @description
         *                 認証されたユーザーの店舗情報を取得します。
         *                 認証されていない場合は、status 401 Unauthorized を返します。(Bodyは StoreErrorResponse)
         *                 ユーザーが持つ店舗情報が存在しない場合は、空のリストを返します。(Bodyは StoreListResponse)
         *
         */
        get: operations["getStoreListByUserId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/store/list/filter/brand": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ブランドIDでフィルタリングした店舗一覧を取得
         * @description
         *                 ブランドIDでフィルタリングした店舗情報を取得します。
         *                 認証されていない場合は、status 401 Unauthorized を返します。(Bodyは StoreErrorResponse)
         *                 ブランドIDが指定されていない場合は、全店舗を返します。(Bodyは StoreListResponse)
         *
         */
        get: operations["getStoreListByBrandId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cognito/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cognito: ユーザー情報を取得
         * @description
         *                 Cognitoを使用して、ユーザーの情報を取得します。
         *                 認証されていない場合は、status 401 Unauthorized を返します。(Bodyは CognitoAccountErrorResponse)
         *                 既に登録されている場合は、status 200 OK を返します。(Bodyは CognitoAccountResponse)
         *
         */
        get: operations["getMe_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/brand/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ユーザーが持つブランド一覧を取得
         * @description
         *                 認証されたユーザーのブランド情報を取得します。
         *                 認証されていない場合は、status 401 Unauthorized を返します。(Bodyは BrandErrorResponse)
         *                 ユーザーが持つブランド情報が存在しない場合は、空のリストを返します。(Bodyは BrandListApiResponse)
         *
         */
        get: operations["getBrandList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/store/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 店舗を削除
         * @description
         *                 認証されたユーザーの店舗を削除します。
         *                 認証されていない場合は、status 401 Unauthorized を返します。(Bodyは StoreErrorResponse)
         *                 店舗の削除に成功した場合は、status 204 No Content を返します。
         *
         */
        delete: operations["deleteStore"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/brand/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * ブランドを削除
         * @description
         *                 認証されたユーザーのブランドを削除します。
         *                 認証されていない場合は、status 401 Unauthorized を返します。(Bodyは BrandErrorResponse)
         *                 ブランドの削除に成功した場合は、status 204 No Content を返します。
         *
         */
        delete: operations["deleteBrand"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /** Format: date-time */
            timestamp: string;
            /** Format: int32 */
            status: number;
            error: string;
            message: string;
            path: string;
        };
        StoreResponse: {
            storeId: string;
            userId: string;
            brandId?: string;
            name: string;
            googleAccountId?: string;
            googleLocationId?: string;
            googleLinkedAt?: string;
            createdAt: string;
        };
        GooglePlacesAutoCompleteRequest: {
            input: string;
        };
        GooglePlacesAutoCompletePlaceSet: {
            placeId?: string;
            text?: string;
        };
        GooglePlacesAutoCompleteResponse: {
            placeSetList?: components["schemas"]["GooglePlacesAutoCompletePlaceSet"][];
        };
        BrandResponse: {
            brandId: string;
            userId: string;
            name: string;
            createdAt: string;
        };
        UserApiResponse: Record<string, never>;
        StoreListResponse: {
            stores: components["schemas"]["StoreResponse"][];
        };
        BrandListResponse: {
            brands: components["schemas"]["BrandResponse"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createStore: {
        parameters: {
            query: {
                storeName: string;
                brandId?: string;
                googleAccountId?: string;
                googleLocationId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StoreResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    postPlacesAutoComplete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GooglePlacesAutoCompleteRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GooglePlacesAutoCompleteResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createBrand: {
        parameters: {
            query: {
                brandName: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BrandResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateStoreName: {
        parameters: {
            query: {
                storeId: string;
                storeName: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StoreResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateStoreGoogle: {
        parameters: {
            query: {
                storeId: string;
                googleAccountId: string;
                googleLocationId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StoreResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateStoreGoogleLocation: {
        parameters: {
            query: {
                storeId: string;
                googleLocationId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StoreResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateStoreGoogleAccount: {
        parameters: {
            query: {
                storeId: string;
                googleAccountId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StoreResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateStoreBrand: {
        parameters: {
            query: {
                storeId: string;
                brandId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StoreResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateBrandName: {
        parameters: {
            query: {
                brandId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BrandResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserApiResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getStore: {
        parameters: {
            query: {
                storeId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StoreResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getStoreListByUserId: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StoreListResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getStoreListByBrandId: {
        parameters: {
            query: {
                brandId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StoreListResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getMe_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getBrandList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BrandListResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteStore: {
        parameters: {
            query: {
                storeId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteBrand: {
        parameters: {
            query: {
                brandId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
