/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/google/location/question": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Google:店舗のQ&Aを追加
         * @description
         *                   Google:店舗のQ&Aを追加します。
         *                   Request Bodyとして textのみ入ったJsonにしてください。
         *                   例 : {"text": "質問内容"}
         *
         */
        post: operations["postLocationQuestion"];
        /**
         * Google:店舗の質問の削除
         * @description
         *                   Google:店舗の質問を削除します。
         *
         */
        delete: operations["deleteLocationQuestion"];
        options?: never;
        head?: never;
        /**
         * Google:店舗のQ&Aの更新
         * @description
         *                   Google:店舗のQ&Aを更新します。
         *                   Request Bodyとして textのみ入ったJsonにしてください。
         *                   例 : {"text": "質問内容"}
         *
         */
        patch: operations["updateLocationQuestion"];
        trace?: never;
    };
    "/api/google/location/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google:店舗の写真を全て取得
         * @description Google:店舗の写真を全て取得します
         */
        get: operations["getLocationPhotos"];
        put?: never;
        /**
         * Google:写真を追加
         * @description Google:店舗の写真を追加します
         */
        post: operations["postLocationPhotos"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/google/location/local_posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google:店舗の最新情報を全て取得
         * @description Google:店舗の最新情報を全て取得します
         */
        get: operations["getLocationLocalPosts"];
        put?: never;
        /**
         * Google:最新情報を追加
         * @description Google:店舗の最新情報を追加します
         */
        post: operations["postLocationLocalPosts"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/google/location/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Google:店舗のQ&Aに回答
         * @description
         *                   Google:店舗のQ&Aに現在のユーザー回答します。すでに回答している場合は回答内容を更新します。
         *                   Request Bodyとして textのみ入ったJsonにしてください。
         *                   例 : {"text": "回答内容"}
         *
         */
        post: operations["postLocationAnswer"];
        /**
         * Google:店舗の回答の削除
         * @description
         *                   Google:現在のユーザーが作成した回答を削除します。
         *
         */
        delete: operations["deleteLocationAnswer"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/google/location/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google:店舗プロフィールの取得
         * @description Google:店舗プロフィールの取得を行います
         */
        get: operations["getLocationProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Google:店舗プロフィールの更新
         * @description Google:店舗プロフィールを更新します
         */
        patch: operations["updateLocationProfile"];
        trace?: never;
    };
    "/api/google/location/profile/website_uri": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Google:店舗のプロフィールの更新:ウェブサイトURL
         * @description
         *                   Google:店舗のウェブサイトURLを更新します。
         *                   Request Bodyとして websiteUriのStringにしてください。
         *                   例 : https://example.com
         *
         */
        patch: operations["updateLocationProfileWebsiteUri"];
        trace?: never;
    };
    "/api/google/location/profile/title": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Google:店舗のプロフィールの更新:ビジネス名
         * @description Google:店舗のビジネス名を更新します
         */
        patch: operations["updateLocationProfileTitle"];
        trace?: never;
    };
    "/api/google/location/profile/phone_number": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Google:店舗のプロフィールの更新:電話番号
         * @description
         *                   Google:店舗の電話番号を更新します。
         *                   Request Bodyとして phoneNumberのStringにしてください。
         *                   数字に変換した時に10桁である必要があります。
         *                   ハイフンとスペースは無視されます。
         *                   例1 : 09012345678
         *                   例2 : 9012345678
         *                   例3 : 090-1234-5678
         *                   例4 : 090 1234 5678
         *
         */
        patch: operations["updateLocationProfilePhoneNumber"];
        trace?: never;
    };
    "/api/google/location/profile/opening_date": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Google:店舗のプロフィールの更新:オープン日
         * @description
         *                   Google:店舗のオープン日を更新します。
         *                   Request Bodyとして dateのみ入ったJsonにしてください。
         *                   例 : {"year": 2023, "month": 10, "day": 1}
         *
         */
        patch: operations["updateLocationProfileOpeningDate"];
        trace?: never;
    };
    "/api/google/location/profile/description": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Google:店舗のプロフィールの更新:説明
         * @description
         *                   Google:店舗の説明を更新します。
         *                   Request Bodyとして descriptionのStringにしてください。
         *                   例 : これは店舗です。
         *
         */
        patch: operations["updateLocationProfileDescription"];
        trace?: never;
    };
    "/api/google/location/profile/additional_categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Google:店舗のプロフィールの更新:追加カテゴリ
         * @description
         *                   Google:店舗の追加カテゴリを更新します。
         *                   Request Bodyとして nameのみ入った配列Jsonにしてください。
         *                   例 :
         *                   [
         *                     {"name": "カテゴリ名"},
         *                     {"name": "カテゴリ名"}
         *                   ]
         *
         */
        patch: operations["updateLocationProfileAdditionalCategories"];
        trace?: never;
    };
    "/api/google/location/prifle/primary_category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Google:店舗のプロフィールの更新:メインカテゴリ
         * @description Google:店舗のメインカテゴリを更新します
         */
        patch: operations["updateLocationProfilePrimaryCategory"];
        trace?: never;
    };
    "/api/google/location/food_menus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google:店舗のメニューを全て取得
         * @description Google:店舗のメニューを全て取得します
         */
        get: operations["getLocationFoodMenus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Google:店舗のメニューの更新
         * @description Google:店舗のメニューを更新します
         */
        patch: operations["updateLocationFoodMenus"];
        trace?: never;
    };
    "/api/google/location/attributes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google:店舗の属性情報を全て取得
         * @description Google:店舗の属性情報を全て取得します
         */
        get: operations["getLocationAttributes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Google:店舗の属性の更新
         * @description
         *                   Google:店舗の属性を更新します。
         *                   Request:
         *                       Params: attributeMaskに更新する属性のカンマ区切りのリストを渡してください。
         *                       例: attributes/url_twitter,attributes/url_tiktok
         *                       Body: nameを除くattributesのJsonを渡してください。attributeMaskに含んでいない属性は無視されます。
         *                       例 : {
         *                           "attributes": [
         *                             {
         *                               "uriValues": [
         *                                 {
         *                                   "uri": "https://x.com/elonmuskkkkkk"
         *                                 }
         *                               ],
         *                               "valueType": "URL",
         *                               "name": "attributes/url_twitter"
         *                             },
         *                             {
         *                               "uriValues": [
         *                                 {
         *                                   "uri": "https://www.tiktok.com/@takafumi_horiekkkkk"
         *                                 }
         *                               ],
         *                               "valueType": "URL",
         *                               "name": "attributes/url_tiktok"
         *                             }
         *                           ]
         *                         }
         *
         */
        patch: operations["updateLocationAttributes"];
        trace?: never;
    };
    "/api/google/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google:ログインユーザー情報の取得
         * @description Google:ログインユーザー情報の取得を行います
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/google/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google:店舗一覧の取得
         * @description Google:店舗一覧の取得を行います
         */
        get: operations["getLocations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/google/location": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google:店舗情報の取得
         * @description Google:店舗情報の取得を行います
         */
        get: operations["getLocation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/google/location/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google:店舗のQ&Aを全て取得
         * @description
         *                Google:店舗のQ&Aを全て取得します。
         *                ビジネスプロフィールが無効だったり制限がかかっている場合はエラーが返ってきます。
         *
         */
        get: operations["getLocationQuestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/google/location/photo/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google:Google API専用
         * @description GoogleAPIに写真をアップロードするときに使用されます
         */
        get: operations["getLocationPhotoLocal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/google/location/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google:店舗のQ&Aの特定の質問に対する回答を全て取得
         * @description
         *                Google:店舗のQ&Aの特定の質問に対する回答を全て取得します。
         *                ビジネスプロフィールが無効だったり制限がかかっている場合はエラーが返ってきます。
         *
         */
        get: operations["getLocationAnswers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/google/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google:カテゴリ一覧の取得
         * @description Google:カテゴリ一覧の取得を行います
         */
        get: operations["getCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/google/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google:アカウント一覧の取得
         * @description Google:アカウント一覧の取得を行います
         */
        get: operations["getAccounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/google/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google:アカウント情報の取得
         * @description Google:アカウント情報の取得を行います
         */
        get: operations["getAccount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        GoogleLocationAnswer: {
            name?: string;
            text?: string;
            createTime?: string;
            updateTime?: string;
            /** Format: int32 */
            upvoteCount?: number;
            author?: components["schemas"]["GoogleLocationAuthor"];
        };
        GoogleLocationAuthor: {
            name?: string;
            profilePhotoUrl?: string;
            /** @enum {string} */
            type?: GoogleLocationAuthorType;
        };
        GoogleLocationQuestion: {
            name?: string;
            text?: string;
            createTime?: string;
            updateTime?: string;
            /** Format: int32 */
            upvoteCount?: number;
            /** Format: int32 */
            totalAnswerCount?: number;
            author?: components["schemas"]["GoogleLocationAuthor"];
            topAnswers?: components["schemas"]["GoogleLocationAnswer"][];
        };
        GoogleLocationAssociation: {
            /** @enum {string} */
            category?: GoogleLocationAssociationCategory;
        };
        GoogleLocationCallToAction: {
            actionType?: string;
            url?: string;
        };
        GoogleLocationDate: {
            /** Format: int32 */
            year?: number;
            /** Format: int32 */
            month?: number;
            /** Format: int32 */
            day?: number;
        };
        GoogleLocationEvent: {
            title?: string;
            schedule?: components["schemas"]["GoogleLocationTimeInterval"];
        };
        GoogleLocationLocalPostModel: {
            name?: string;
            languageCode?: string;
            summary?: string;
            callToAction?: components["schemas"]["GoogleLocationCallToAction"];
            createTime?: string;
            updateTime?: string;
            event?: components["schemas"]["GoogleLocationEvent"];
            state?: string;
            media?: components["schemas"]["GoogleLocationPhotoModel"][];
            searchUrl?: string;
            topicType?: string;
            alertType?: string;
            offer?: components["schemas"]["GoogleLocationOffer"];
        };
        GoogleLocationOffer: {
            couponCode?: string;
            redeemOnlineUrl?: string;
            termsConditions?: string;
        };
        GoogleLocationPhotoDataRef: {
            resourceName?: string;
        };
        GoogleLocationPhotoModel: {
            name?: string;
            mediaFormat?: string;
            googleUrl?: string;
            thumbnailUrl?: string;
            createTime?: string;
            locationAssociation?: components["schemas"]["GoogleLocationAssociation"];
            dataRef?: components["schemas"]["GoogleLocationPhotoDataRef"];
            sourceUrl?: string;
        };
        GoogleLocationTimeInterval: {
            startDate?: components["schemas"]["GoogleLocationDate"];
            endDate?: components["schemas"]["GoogleLocationDate"];
            startTime?: components["schemas"]["GoogleLocationTimeOfDay"];
            endTime?: components["schemas"]["GoogleLocationTimeOfDay"];
        };
        GoogleLocationTimeOfDay: {
            /** Format: int32 */
            hours?: number;
            /** Format: int32 */
            minutes?: number;
            /** Format: int32 */
            seconds?: number;
            /** Format: int32 */
            nanos?: number;
        };
        GoogleLocationCategories: {
            primaryCategory?: components["schemas"]["GoogleLocationCategory"];
            additionalCategories?: components["schemas"]["GoogleLocationCategory"][];
        };
        GoogleLocationCategory: {
            name?: string;
            displayName?: string;
        };
        GoogleLocationOpenInfo: {
            status?: string;
            canReopen?: boolean;
            openingDate?: components["schemas"]["GoogleLocationDate"];
        };
        GoogleLocationPhoneNumbers: {
            primaryPhone?: string;
            additionalPhones?: string[];
        };
        GoogleLocationPlaceInfo: {
            placeName?: string;
            placeId?: string;
        };
        GoogleLocationPlaceInfos: {
            placeInfos?: components["schemas"]["GoogleLocationPlaceInfo"][];
        };
        GoogleLocationProfile: {
            description?: string;
        };
        GoogleLocationProfileModel: {
            name?: string;
            title?: string;
            phoneNumbers?: components["schemas"]["GoogleLocationPhoneNumbers"];
            categories?: components["schemas"]["GoogleLocationCategories"];
            websiteUri?: string;
            profile?: components["schemas"]["GoogleLocationProfile"];
            openInfo?: components["schemas"]["GoogleLocationOpenInfo"];
            serviceArea?: components["schemas"]["GoogleLocationServiceArea"];
        };
        GoogleLocationServiceArea: {
            businessType?: string;
            regionCode?: string;
            places?: components["schemas"]["GoogleLocationPlaceInfos"];
        };
        GoogleLocationCaloriesFact: {
            /** Format: int32 */
            lowerAmount?: number;
            /** Format: int32 */
            upperAmount?: number;
            unit?: string;
        };
        GoogleLocationFoodMenu: {
            labels?: components["schemas"]["GoogleLocationMenuLabel"][];
            sourceUrl?: string;
            sections?: components["schemas"]["GoogleLocationFoodMenuSection"][];
            cuisines?: string[];
        };
        GoogleLocationFoodMenuItem: {
            labels?: components["schemas"]["GoogleLocationMenuLabel"][];
            attributes?: components["schemas"]["GoogleLocationFoodMenuItemAttributes"];
            options?: components["schemas"]["GoogleLocationFoodMenuItemOption"][];
        };
        GoogleLocationFoodMenuItemAttributes: {
            price?: components["schemas"]["GoogleLocationMoney"];
            spiciness?: string;
            allergen?: string[];
            dietaryRestriction?: string[];
            nutritionFacts?: components["schemas"]["GoogleLocationNutritionFacts"];
            ingredients?: components["schemas"]["GoogleLocationIngredient"][];
            /** Format: int32 */
            servesNumPeople?: number;
            preparationMethods?: string[];
            portionSize?: components["schemas"]["GoogleLocationPortionSize"];
            mediaKeys?: string[];
        };
        GoogleLocationFoodMenuItemOption: {
            labels?: components["schemas"]["GoogleLocationMenuLabel"][];
            attributes?: components["schemas"]["GoogleLocationFoodMenuItemAttributes"];
        };
        GoogleLocationFoodMenuSection: {
            labels?: components["schemas"]["GoogleLocationMenuLabel"][];
            items?: components["schemas"]["GoogleLocationFoodMenuItem"][];
        };
        GoogleLocationFoodMenusModel: {
            name?: string;
            menus?: components["schemas"]["GoogleLocationFoodMenu"][];
        };
        GoogleLocationIngredient: {
            labels?: components["schemas"]["GoogleLocationMenuLabel"][];
        };
        GoogleLocationMenuLabel: {
            displayName?: string;
            description?: string;
            languageCode?: string;
        };
        GoogleLocationMoney: {
            currencyCode?: string;
            units?: string;
            /** Format: int32 */
            nanos?: number;
        };
        GoogleLocationNutritionFact: {
            /** Format: int32 */
            lowerAmount?: number;
            /** Format: int32 */
            upperAmount?: number;
            unit?: string;
        };
        GoogleLocationNutritionFacts: {
            calories?: components["schemas"]["GoogleLocationCaloriesFact"];
            totalFat?: components["schemas"]["GoogleLocationNutritionFact"];
            cholesterol?: components["schemas"]["GoogleLocationNutritionFact"];
            sodium?: components["schemas"]["GoogleLocationNutritionFact"];
            totalCarbohydrates?: components["schemas"]["GoogleLocationNutritionFact"];
            protein?: components["schemas"]["GoogleLocationNutritionFact"];
        };
        GoogleLocationPortionSize: {
            /** Format: int32 */
            quantity?: number;
            unit?: components["schemas"]["GoogleLocationMenuLabel"][];
        };
        GoogleLocationAttribute: {
            name?: string;
            /** @enum {string} */
            valueType?: GoogleLocationAttributeValueType;
            uriValues?: components["schemas"]["GoogleLocationAttributeUriValue"][];
        };
        GoogleLocationAttributeUriValue: {
            uri?: string;
        };
        GoogleLocationAttributesModel: {
            name?: string;
            attributes?: components["schemas"]["GoogleLocationAttribute"][];
        };
        GoogleMe: {
            names: components["schemas"]["GoogleName"][];
        };
        GoogleName: {
            displayName: string;
            familyName?: string;
            givenName?: string;
        };
        GoogleLocation: {
            name: string;
            title: string;
        };
        StreamingResponseBody: Record<string, never>;
        GoogleAccount: {
            name: string;
            accountName: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    postLocationQuestion: {
        parameters: {
            query: {
                locationId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleLocationQuestion"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteLocationQuestion: {
        parameters: {
            query: {
                locationId: string;
                questionId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateLocationQuestion: {
        parameters: {
            query: {
                locationId: string;
                questionId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleLocationQuestion"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GoogleLocationQuestion"];
                };
            };
        };
    };
    getLocationPhotos: {
        parameters: {
            query: {
                accountId: string;
                locationId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GoogleLocationPhotoModel"][];
                };
            };
        };
    };
    postLocationPhotos: {
        parameters: {
            query: {
                accountId: string;
                locationId: string;
                files: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getLocationLocalPosts: {
        parameters: {
            query: {
                accountId: string;
                locationId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GoogleLocationLocalPostModel"][];
                };
            };
        };
    };
    postLocationLocalPosts: {
        parameters: {
            query: {
                accountId: string;
                locationId: string;
                files: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleLocationLocalPostModel"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postLocationAnswer: {
        parameters: {
            query: {
                locationId: string;
                questionId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleLocationAnswer"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteLocationAnswer: {
        parameters: {
            query: {
                locationId: string;
                questionId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getLocationProfile: {
        parameters: {
            query: {
                locationId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GoogleLocationProfileModel"];
                };
            };
        };
    };
    updateLocationProfile: {
        parameters: {
            query: {
                locationId: string;
                updateMask: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleLocationProfileModel"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GoogleLocationProfileModel"];
                };
            };
        };
    };
    updateLocationProfileWebsiteUri: {
        parameters: {
            query: {
                locationId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GoogleLocationProfileModel"];
                };
            };
        };
    };
    updateLocationProfileTitle: {
        parameters: {
            query: {
                locationId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GoogleLocationProfileModel"];
                };
            };
        };
    };
    updateLocationProfilePhoneNumber: {
        parameters: {
            query: {
                locationId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GoogleLocationProfileModel"];
                };
            };
        };
    };
    updateLocationProfileOpeningDate: {
        parameters: {
            query: {
                locationId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleLocationDate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GoogleLocationProfileModel"];
                };
            };
        };
    };
    updateLocationProfileDescription: {
        parameters: {
            query: {
                locationId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GoogleLocationProfileModel"];
                };
            };
        };
    };
    updateLocationProfileAdditionalCategories: {
        parameters: {
            query: {
                locationId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleLocationCategory"][];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GoogleLocationProfileModel"];
                };
            };
        };
    };
    updateLocationProfilePrimaryCategory: {
        parameters: {
            query: {
                locationId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleLocationCategory"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GoogleLocationProfileModel"];
                };
            };
        };
    };
    getLocationFoodMenus: {
        parameters: {
            query: {
                accountId: string;
                locationId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GoogleLocationFoodMenusModel"];
                };
            };
        };
    };
    updateLocationFoodMenus: {
        parameters: {
            query: {
                accountId: string;
                locationId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleLocationFoodMenusModel"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GoogleLocationFoodMenusModel"];
                };
            };
        };
    };
    getLocationAttributes: {
        parameters: {
            query: {
                locationId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GoogleLocationAttributesModel"];
                };
            };
        };
    };
    updateLocationAttributes: {
        parameters: {
            query: {
                locationId: string;
                attributeMask: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleLocationAttributesModel"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GoogleLocationAttributesModel"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GoogleMe"];
                };
            };
        };
    };
    getLocations: {
        parameters: {
            query: {
                accountId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GoogleLocation"][];
                };
            };
        };
    };
    getLocation: {
        parameters: {
            query: {
                locationId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GoogleLocation"];
                };
            };
        };
    };
    getLocationQuestions: {
        parameters: {
            query: {
                locationId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GoogleLocationQuestion"][];
                };
            };
        };
    };
    getLocationPhotoLocal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StreamingResponseBody"];
                };
            };
        };
    };
    getLocationAnswers: {
        parameters: {
            query: {
                locationId: string;
                questionId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GoogleLocationAnswer"][];
                };
            };
        };
    };
    getCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GoogleLocationCategory"][];
                };
            };
        };
    };
    getAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GoogleAccount"][];
                };
            };
        };
    };
    getAccount: {
        parameters: {
            query: {
                accountId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GoogleAccount"];
                };
            };
        };
    };
}
export enum GoogleLocationAuthorType {
    AUTHOR_TYPE_UNSPECIFIED = "AUTHOR_TYPE_UNSPECIFIED",
    REGULAR_USER = "REGULAR_USER",
    LOCAL_GUIDE = "LOCAL_GUIDE",
    MERCHANT = "MERCHANT"
}
export enum GoogleLocationAssociationCategory {
    COVER = "COVER",
    PROFILE = "PROFILE",
    LOGO = "LOGO",
    EXTERIOR = "EXTERIOR",
    INTERIOR = "INTERIOR",
    PRODUCT = "PRODUCT",
    AT_WORK = "AT_WORK",
    FOOD_AND_DRINK = "FOOD_AND_DRINK",
    MENU = "MENU",
    ROOMS = "ROOMS",
    TEAMS = "TEAMS",
    ADDITIONAL = "ADDITIONAL",
    CATEGORY_UNSPECIFIED = "CATEGORY_UNSPECIFIED"
}
export enum GoogleLocationAttributeValueType {
    ATTRIBUTE_VALUE_TYPE_UNSPECIFIED = "ATTRIBUTE_VALUE_TYPE_UNSPECIFIED",
    URL = "URL",
    BOOL = "BOOL",
    ENUM = "ENUM",
    REPEATED_ENUM = "REPEATED_ENUM"
}
