
CREATE TABLE IF NOT EXISTS MENU_LOGS (
    id SERIAL PRIMARY KEY,
    userName VARCHAR(255) NOT NULL,
    locationId VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    menu JSONB NOT NULL
);