app:
  redirect:
    url: https://cmssoel.click/edit

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "https://cmssoel.click/login/oauth2/code/google"