spring:
  application:
    name: backend
  profiles:
    active: local
  web:
    resources:
      cache:
        cachecontrol:
          no-store: true
  
  security:
    oauth2:
      client:
        registration:
#          facebook:
#            client-id: ${FACEBOOK_CLIENT_ID}
#            client-secret: ${FACEBOOK_CLIENT_SECRET}
#            scope: ${FACEBOOK_SCOPE}
#            redirect-uri: "{baseUrl}/login/oauth2/code/facebook"
          google:
            client-id: 666193583764-vqto55avfkdtn0nqj0j74j7jti8o281s.apps.googleusercontent.com
            client-secret: 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
            scope: openid,profile,https://www.googleapis.com/auth/business.manage
#            redirect-uri: "{baseUrl}/login/oauth2/code/google"
#        provider:
#          facebook:
#            authorization-uri: https://www.facebook.com/v20.0/dialog/oauth
#            token-uri: https://graph.facebook.com/v20.0/oauth/access_token


logging:
  level:
    org.springframework.web.cors: DEBUG