app:
  redirect:
    url: http://localhost:5173/edit
  base-url: http://localhost:5173

spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            redirect-uri: "http://localhost:8080/login/oauth2/code/cognito"
          google:
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
