name: Build Image

on:
  workflow_dispatch:

  pull_request:
    branches: [ main ]

  push:
    branches:
      - feature/infra/develop

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_exists: ${{ steps.check.outputs.image_exists }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo "ENV=dev" >> $GITHUB_ENV
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "IMAGE_TAG=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Run Blue/Green Deploy at that commit
        id: get-ecr-uri
        run: |
          cd infra
          pwd
          echo ${ENV}
          echo ${IMAGE_TAG}
          chmod +x ./scripts/900-deploy-app.sh
          ./scripts/900-deploy-app.sh "${ENV}" "${IMAGE_TAG}"
