name: Deploy App to Prod on tag push

on:
  push:
    tags:
      - "*"  # すべてのタグで起動（必要に応じて 'v*' 等、パターンで絞る）

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo "ENV=prd" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV  # 付与されたタグ名を使用

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Build and Push app-image
        run: |
          cd infra
          chmod +x ./scripts/push-image.sh
          ./scripts/push-image.sh "${ENV}" "${IMAGE_TAG}"

      - name: Run Blue/Green Deploy at that commit
        run: |
          cd infra
          chmod +x ./scripts/deploy-app.sh
          ./scripts/deploy-app.sh "${ENV}" "${IMAGE_TAG}"
